.DEFAULT_SWAP_WITHIN <- "1"
.DEFAULT_SPATIAL_FACTORS <- ~ row + col
.DEFAULT_GRID_FACTORS <- list(dim1 = "row", dim2 = "col")
.DEFAULT_ITERATIONS <- 10000
.DEFAULT_EARLY_STOP_ITERATIONS <- 2000
.DEFAULT_SWAP_ALL <- FALSE
